model_params:
  name: "VectorVAEnLayers"
  in_channels: 3
  latent_dim: 256
  loss_fn: 'MSE'
  paths: 20
  beta: 0
  radius: 3
  scale_factor: 1
  learn_sampling: False
  only_auxiliary_training: False
  memory_leak_training: False
  other_losses_weight: 1

exp_params:
  dataset: covers
  data_path: "./data/covers/"
  img_size: 128
  batch_size: 64 # Better to have a square number
  val_batch_size: 256 # Better to have a square number
  val_shuffle: True
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  grow: True

trainer_params:
  gpus: 1
  max_epochs: 2500

logging_params:
  save_dir: "logs/"
  other_interpolations: True
  name: "VectorVAEnLayers"
  version: 110
  manual_seed: 1265
